"""
baseline_model.py  —  Train and evaluate the reference baseline model.

Run AFTER split_dataset.py has produced the train/val CSVs and
fetch_structures.py has produced cif_files/.

Uses MAGPIE composition featurization from matminer plus two separate
RandomForestRegressor models (one per property). The resulting validation
MAEs become the normalization constants for the Codabench scoring function.

Inputs:
    bridge_dataset_train.csv
    bridge_dataset_val.csv

Outputs:
    baseline_model_ef.joblib        formation energy model
    baseline_model_bg.joblib        band gap model
    baseline_results.csv            val predictions + true values
    baseline_constants.py           BASELINE_MAE_EF / BASELINE_MAE_BG for evaluate.py
"""

import joblib
import numpy as np
import pandas as pd
from matminer.featurizers.composition import ElementProperty
from pymatgen.core import Composition
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# ── load data ─────────────────────────────────────────────────────────────────

print("Loading data...")
train = pd.read_csv("bridge_dataset_train.csv")
val   = pd.read_csv("bridge_dataset_val.csv")
print(f"  train: {len(train):,}  val: {len(val):,}")

# ── featurize ─────────────────────────────────────────────────────────────────

print("Featurizing with MAGPIE (ElementProperty)...")
featurizer = ElementProperty.from_preset("magpie")
featurizer.set_n_jobs(1)

def featurize(df: pd.DataFrame) -> np.ndarray:
    structs = [Composition(f) for f in df["formula"]]
    features = [featurizer.featurize(c) for c in structs]
    return np.array(features)

X_train = featurize(train)
X_val   = featurize(val)
print(f"  Feature vector length: {X_train.shape[1]}")

y_train_ef = train["formation_energy_per_atom_label"].values
y_train_bg = train["band_gap_label"].values
y_val_ef   = val["formation_energy_per_atom_label"].values
y_val_bg   = val["band_gap_label"].values

# ── train ──────────────────────────────────────────────────────────────────────

print("Training formation energy model (RandomForest, n_estimators=100)...")
rf_ef = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_ef.fit(X_train, y_train_ef)

print("Training band gap model...")
rf_bg = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_bg.fit(X_train, y_train_bg)

# ── evaluate on validation set ────────────────────────────────────────────────

pred_ef = rf_ef.predict(X_val)
pred_bg = rf_bg.predict(X_val)

mae_ef = mean_absolute_error(y_val_ef, pred_ef)
mae_bg = mean_absolute_error(y_val_bg, pred_bg)

print(f"\nValidation MAE:")
print(f"  Formation energy : {mae_ef:.4f} eV/atom")
print(f"  Band gap         : {mae_bg:.4f} eV")

# ── save outputs ───────────────────────────────────────────────────────────────

joblib.dump(rf_ef, "baseline_model_ef.joblib")
joblib.dump(rf_bg, "baseline_model_bg.joblib")
print("\nSaved baseline_model_ef.joblib, baseline_model_bg.joblib")

results = val[["material_id", "formula",
               "formation_energy_per_atom_label", "band_gap_label"]].copy()
results["pred_formation_energy"] = pred_ef
results["pred_band_gap"]         = pred_bg
results.to_csv("baseline_results.csv", index=False)
print("Saved baseline_results.csv")

# Write normalization constants so evaluate.py can import them without hardcoding
constants_src = f'''\
# baseline_constants.py  —  auto-generated by baseline_model.py
# Update evaluate.py in the Codabench bundle with these values.
BASELINE_MAE_EF = {mae_ef:.4f}   # eV/atom — formation energy
BASELINE_MAE_BG = {mae_bg:.4f}   # eV       — band gap
PERFECT_MAE     = 0.01           # theoretical minimum for scoring normalization
'''
with open("baseline_constants.py", "w") as f:
    f.write(constants_src)
print("Saved baseline_constants.py")
print("\nCopy BASELINE_MAE_EF and BASELINE_MAE_BG into evaluation_bundle/scoring_program/evaluate.py")
